// src/properties.js
export const properties = [
    { name: "Go", type: "corner", pos: [1, 11] },
    { name: "Mediterranean Avenue", type: "property", color: "brown", pos: [1, 10] },
    { name: "Community Chest", type: "property", pos: [1, 9] },
    { name: "Baltic Avenue", type: "property", color: "brown", pos: [1, 8] },
    { name: "Income Tax", type: "property", pos: [1, 7] },
    { name: "Reading Railroad", type: "property", pos: [1, 6] },
    { name: "Oriental Avenue", type: "property", color: "light-blue", pos: [1, 5] },
    { name: "Chance", type: "property", pos: [1, 4] },
    { name: "Vermont Avenue", type: "property", color: "light-blue", pos: [1, 3] },
    { name: "Connecticut Avenue", type: "property", color: "light-blue", pos: [1, 2] },
    { name: "Jail", type: "corner", pos: [1, 1] },
    { name: "St. Charles Place", type: "property", color: "pink", pos: [2, 1] },
    { name: "Electric Company", type: "property", pos: [3, 1] },
    { name: "States Avenue", type: "property", color: "pink", pos: [4, 1] },
    { name: "Virginia Avenue", type: "property", color: "pink", pos: [5, 1] },
    { name: "Pennsylvania Railroad", type: "property", pos: [6, 1] },
    { name: "St. James Place", type: "property", color: "orange", pos: [7, 1] },
    { name: "Community Chest", type: "property", pos: [8, 1] },
    { name: "Tennessee Avenue", type: "property", color: "orange", pos: [9, 1] },
    { name: "New York Avenue", type: "property", color: "orange", pos: [10, 1] },
    { name: "Free Parking", type: "corner", pos: [11, 1] },
    { name: "Kentucky Avenue", type: "property", color: "red", pos: [11, 2] },
    { name: "Chance", type: "property", pos: [11, 3] },
    { name: "Indiana Avenue", type: "property", color: "red", pos: [11, 4] },
    { name: "Illinois Avenue", type: "property", color: "red", pos: [11, 5] },
    { name: "B&O Railroad", type: "property", pos: [11, 6] },
    { name: "Atlantic Avenue", type: "property", color: "yellow", pos: [11, 7] },
    { name: "Ventnor Avenue", type: "property", color: "yellow", pos: [11, 8] },
    { name: "Water Works", type: "property", pos: [11, 9] },
    { name: "Marvin Gardens", type: "property", color: "yellow", pos: [11, 10] },
    { name: "Go To Jail", type: "corner", pos: [11, 11] },
    { name: "Pacific Avenue", type: "property", color: "green", pos: [10, 11] },
    { name: "North Carolina Avenue", type: "property", color: "green", pos: [9, 11] },
    { name: "Community Chest", type: "property", pos: [8, 11] },
    { name: "Pennsylvania Avenue", type: "property", color: "green", pos: [7, 11] },
    { name: "Short Line", type: "property", pos: [6, 11] },
    { name: "Chance", type: "property", pos: [5, 11] },
    { name: "Park Place", type: "property", color: "blue", pos: [4, 11] },
    { name: "Luxury Tax", type: "property", pos: [3, 11] },
    { name: "Boardwalk", type: "property", color: "blue", pos: [2, 11] }
  ];